---
name: Release Container

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release-container:
    permissions:
      contents: read
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-release-container.yml@b2a8dc74e6ec2ea664c769af9f8a01de829596bc # v3.1.0
