---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@bca4a88baa1c0e775ce02fca3673280011633946 # testing trivy download
    with:
      runtime: python
