---
name: Test Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test-container:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-test-container.yml@42bc0159e43ebec0a6eb944c875d78f28ab6fa8a # v5.0.0
    with:
      clean-runner: true
